.clone project:
  image: luzhzh/git-client
  stage: clone 
  variables:
    GIT_STRATEGY: none
    PROJECT_NAME: ""
    PROJECT_GROUP: ""
  artifacts:
    expire_in: 20min
    paths:
      - ${PROJECT_NAME}
  script: 
  - env 
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/${PROJECT_GROUP}/${PROJECT_NAME}.git
  - cd ${PROJECT_NAME}
  - branch=$(git ls-remote https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/${PROJECT_GROUP}/${PROJECT_NAME}.git ${CI_COMMIT_REF_NAME})
  - echo $branch
  - if test "$branch" != ""  ; then git checkout ${CI_COMMIT_REF_NAME} ; else git checkout master; fi
  - git branch 
  - cd ..