build app:
    image: node
    stage: build
    variables:
        FOLDER_BUILD: build
        FOLDER_PROJECT: project
    cache:
        key: app-build
        policy: push
        paths:
            - build/
    before_script:
        - rm -rf .git/
    script:
        - cd ..
        - mkdir ${FOLDER_BUILD} && mkdir ${FOLDER_PROJECT}
        - tar -zcvf ${FOLDER_BUILD}/${CI_PROJECT_NAME}.tar.gz ${CI_PROJECT_NAME}
        - cp -r ${CI_PROJECT_NAME}/* ${FOLDER_PROJECT}
        - mv ${FOLDER_PROJECT} ${CI_PROJECT_NAME}
        - mv ${FOLDER_BUILD} ${CI_PROJECT_NAME}
        - cd ${CI_PROJECT_NAME}
        - mv ${FOLDER_PROJECT} ${CI_PROJECT_NAME}
